# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbs_up',
            field=models.IntegerField(default=1),
        ),
    ]
